### ISSUE TITLE
yarn installation link failed 

### ISSUE THREAD

**Issue by Neuromancer43** [EvoEvolver/evomark-framework#3]
Yarn install link:
```
Then, yarn can be installed by the installer in https://classic.yarnpkg.com/latest.msi. You may need to restart to make the installations into effect.
```
returns 404 error

**Comment by Neuromancer43** [comment]
The [yarn document](https://classic.yarnpkg.com/lang/en/docs/install/#windows-stable) suggest to install with 
`npm install --global yarn`

**Comment by doomspec** [comment]
Yes, these is a issue with yarn's .msi release link. They didn't maintain that. We may solve the problem by #4
